version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/extractpdf
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-better-auth-secret-123456789}
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: extractpdf
    ports:
      - "5432:5432"
